### ISSUE TITLE
No Controller for New Nodes Added via addChild

### ISSUE THREAD

**Issue by dpollastrini** [valor-software/ng2-tree#204] opened 2018-01-31 00:51 UTC
`  updateCampaignScriptTreeModel(script: IScript): void {

    let targetScriptNodeController: TreeController = this.scriptTreeComponent.getControllerByNodeId(script.id);

    if (targetScriptNodeController) {

      let targetScriptTreeModel = targetScriptNodeController.toTreeModel();

      if (targetScriptTreeModel.title !== script.title) {
        targetScriptNodeController.rename(script.title);
      }
    }
    else {
      let targetParentScriptNodeController: TreeController = this.scriptTreeComponent.getControllerByNodeId(script.parentScriptId);

      if (!targetParentScriptNodeController) {
        targetParentScriptNodeController = this.scriptTreeComponent.rootComponent.controller;
      }

      targetParentScriptNodeController.addChild({ id: script.id, value: script.title, children: [] });
      targetParentScriptNodeController.expand();

      let addedScriptModelController: TreeController = this.scriptTreeComponent.getControllerByNodeId(script.id);
      addedScriptModelController.select();
    }
  }`

I'm dynamically updating a TreeModel based on an arbitrary data model object ("script" in the example above).  When using "addChild" in the above, I note that the children are added to the correct parent TreeModel as expected and the added nodes appear correctly in my tree.

However, it seems no new TreeController is added to the TreeService.controllers collection as part of the addChild function (I have verified this in a debugger).  Consequently, the subsequent call to get the "addedScriptModelController" returns a null.  Per the code my intent in this case is to "select" the newly created node after it is added.  Obviously, relying on the rest of the API also requires access to an existing node controller for newly "added" nodes.

Am I doing something wrong here, or are there design limitations that prevent controllers from being added as part of of the addChild function?

**Comment by dpollastrini** [comment] 2018-01-31 16:49
I found my problem.  I needed to use "createNode" rather than passing an anonymous object directly in to addChild.

` ...
     let newNode = this.scriptTreeComponent.tree.createNode(true, { id: script.id, value: script.title, children: [] });

      targetParentScriptNodeController.addChild(newNode);
...
`

**Comment by rychkog** [comment] 2018-02-05 05:43
@dpollastrini Thanks for sharing - this is a good case for the paragraph in the documentation.

**Comment by boban984** [comment] 2018-02-05 21:54
Hi guys, im having the same issue, but the code sample by @dpollastrini did not work form me.

tree-controller -> addChild already calls "createNode", but the problem is that id does not create a controller for the corresponding new node, as in where you initialize the component with a treeModel id loops trough all the nodes creates a tree-internal instance and also a controller.

```typescript
public addChild(newNode: TreeModel): void {
    if (this.tree.hasDeferredChildren() && !this.tree.childrenWereLoaded()) {
      return;
    }

    const newTree = this.tree.createNode(Array.isArray(newNode.children), newNode);
    this.treeService.fireNodeCreated(newTree);
  }
```

So in my case given a starting multi level nested treeModel everything works great.
But if i try to add child nodes programatically it will fail cause the new nodes won't have controllers and hence you cannot add children nodes to those created before.

A sample tree model would be something like:
1
 .... 1.1
........... 1.1.1
............ 1.1.2

@rychkog Have you managed to create such a structure using "addChild"?

**Comment by rychkog** [comment] 2018-02-06 09:59
@boban984 thanks, I'll reopen this and have a look.

**Comment by rychkog** [comment] 2018-02-11 16:37
@dpollastrini @boban984 TreeController requires TreeInternalComponent in order to control its behavior. But I have an idea. I'll add a createChildAsync method to the controller, therefore allowing TreeInternalComponent to create a new controller for the child on one event loop iteration and resolving the new child on a subsequent one.

Here is the how it will look like:

```typescript
this.treeFFS.getControllerByNodeId(1)
  .addChildAsync({id: 'Boo!', value: 'Casper :)'})
    .then(casper => this.treeFFS.getControllerByNodeId('Boo!').select());
```

What do you think about this, will it resolve your issues?

**Closed** 2018-02-11 17:01 UTC
Labels: bug, documentation needed

**Comment by boban984** [comment] 2018-02-15 15:27
@rychkog that would be ideal

**Comment by rychkog** [comment] 2018-02-15 18:37
@boban984 Actually this functionality is already in master and released. I just haven't had enough time for updating the doc.
