### ISSUE TITLE
Nodes with same parent can't be moved into one another

### ISSUE THREAD

**Issue by Mantaspetr** [valor-software/ng2-tree#206] opened 2018-01-31 13:57 UTC
Moving a node to a folder that shares the same parent with the moved node causes nodes to be reordered rather than moved. You can check this in the demo by dragging folders around that share the same parent, for example: try moving 'Aspect-oriented programming' folder into 'Object-oriented programming'.

**Comment by rychkog** [comment] 2018-02-03 21:06
@Mantaspetr It is by design. We should add additional option for that in order to control this behavior
It is duplicate of https://github.com/valor-software/ng2-tree/issues/68

**Closed** 2018-02-03 21:07 UTC
Labels: duplicate
